---
###############################################################################
# Helm
###############################################################################

helm_version: "v3.19.0"

###############################################################################
# kube-prometheus-stack
###############################################################################

prometheus_namespace: monitoring

kube_prometheus_stack_version: "87.17.0"

grafana_enabled: true

alertmanager_enabled: true

prometheus_enabled: true