apiVersion: v1
kind: Pod
metadata:
  name: netperf-client
  namespace: kubeproxy-test
spec:
  nodeSelector:
    kubernetes.io/hostname: rke2-master
  containers:
  - name: netperf
    image: cilium/netperf
    command:
      - sleep
      - infinity