apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  namespace: bandwidth-test
  labels:
    app: iperf-server
  annotations:
    kubernetes.io/egress-bandwidth: "10M"
    kubernetes.io/ingress-bandwidth: "20M"
spec:
  nodeSelector:
    kubernetes.io/hostname: rke2-worker
  containers:
  - name: iperf
    image: cilium/netperf
    args:
      - iperf3
      - "-s"
    ports:
    - containerPort: 5201