---
###############################################################################
# Hubble CLI
###############################################################################

hubble_cli_arch: amd64
hubble_cli_os: linux