---
###############################################################################
# RKE2 Installation
###############################################################################

rke2_channel: stable

rke2_version: v1.34.1+rke2r1

###############################################################################
# Cluster
###############################################################################

cluster_name: kubernetes-networking-ebpf

###############################################################################
# Networking
###############################################################################

cluster_cidr: "10.42.0.0/16"

service_cidr: "10.43.0.0/16"

cluster_dns: "10.43.0.10"

###############################################################################
# API Server
###############################################################################

write_kubeconfig_mode: "0644"